### ISSUE TITLE
Win 7 

### ISSUE THREAD

**Issue by harryray33** [slater1/BrowseRouter#16]
Does this work with Win 7 and older versions of Firefox?

Thanks

**Comment by slater1** [comment]
Hi @harryray33 ,

For now, BrowseRouter targets net6.0-windows which [according to Microsoft ](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) runs on Windows 7 SP1. However we may at any time update a newer version of .NET.

You might try [BrowserSelector](https://github.com/DanTup/BrowserSelector/), which targets .NET Framework 4.5, which [supports Windows 7](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-45). Moreover, BrowserSelector is no longer maintained, so it will always target .NET Framework 4.5.

**Comment by sergeevabc** [comment]
Err... BrowseRouter 0.6.0.0 does not work on Windows 7, simply outputs blank screen.

However, I'm sure it is possible *for you* to make it work with a slight change in compilation process. Come on, think of a solution for a broader audience, not just 'my app is so cool as it uses the latest shiny libraries'. Obviously, there is *nothing* this app needs from Windows 10 what doesn't exist in Windows 7. For example, Powershell [7.2.17](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.17) (built on 2023-11-16) uses .NET 6.0.417 and it works fine here.

**Comment by nref** [comment]
Version 0.7.0.0 was just released which upgraded BrowseRouter from .NET 6.0 to .NET 8.0. Therefore, BrowserRouter only supports Windows 7 on versions 0.6.0.0 and earlier.

 https://github.com/nref/BrowseRouter/releases/tag/0.7.0.0
