### ISSUE TITLE
Outlook doesn't obey BrowseRouter for links clicked in new windows

### ISSUE THREAD

**Issue by epiphanyplx** [slater1/BrowseRouter#7]
I think this is probably less a problem with BrowseRouter and more a failure of mine to understand where the names in [sources] inside config.ini come from.

Here is the relevant section of my config.ini:
```[sources]
*Microsoft Teams* = chrome
*Outlook* = chrome
*message* = chrome
```

I tried adding `*message*` to see if it would make a difference as that looks to be part of the title of the window but it did not help. 
Is there an easy way to find out the window title of an open program?
I tried using `Get-Process | Where-Object {$_.mainWindowTitle} | Format-Table Id, Name, mainWindowtitle -AutoSize` and found this: 

`246968 OUTLOOK              SSL Expiry in about 2 months - Message (Plain Text)`

So it seems like `*message*` would work in this case.
Any ideas?

**Comment by slater1** [comment]
Hey @epiphanyplx 

I think the sources are case-sensitive. Can you try this?

```ini
[sources]
*Message* = chrome
```

**Comment by epiphanyplx** [comment]
@slater1 Yep, that was it. Thanks!
